### ISSUE TITLE
Mac docker issue

### ISSUE THREAD

**Issue by shogowarrior** [mainsail-crew/virtual-klipper-printer#18]
Hi,

I am able to access `8110` for webcam but moonraker on `7125` fails with:

```
2023-05-30 20:08:59,291 [machine.py:_find_public_ip()] - Detected Local IP: 172.19.0.2
2023-05-30 20:08:59,291 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://172.19.0.2
2023-05-30 20:08:59,296 [shell_command.py:_check_proc_success()] - Command (systemctl status 5685) exited with return code 1
2023-05-30 20:08:59,797 [machine.py:extract_service_info()] - Error extracting service info
Traceback (most recent call last):
  File "/home/printer/moonraker/moonraker/components/machine.py", line 944, in extract_service_info
    resp: str = await self.shell_cmd.exec_cmd(
  File "/home/printer/moonraker/moonraker/components/shell_command.py", line 278, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'systemctl status 5685'
2023-05-30 20:08:59,798 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2023-05-30 20:08:59,798 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2023-05-30 20:08:59,798 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2023-05-30 20:08:59,798 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://172.19.0.2
2023-05-30 20:08:59,798 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2023-05-30 20:08:59,798 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2023-05-30 20:08:59,801 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2023-05-30 20:08:59,803 [shell_command.py:_check_proc_success()] - Command (sh -c 'command -v apt') successfully finished
2023-05-30 20:08:59,803 [update_manager.py:initialize()] - PackageDeploy: Using APT CLI Provider
2023-05-30 20:08:59,805 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/printer/printer_data/comms/moonraker.sock'
2023-05-30 20:08:59,807 [eventloop.py:_wrapper()] - Error Running Callback
Traceback (most recent call last):
  File "/home/printer/moonraker/moonraker/eventloop.py", line 73, in _wrapper
    await ret
  File "/home/printer/moonraker/moonraker/server.py", line 181, in server_init
    await self.start_server()
  File "/home/printer/moonraker/moonraker/server.py", line 186, in start_server
    await extm.start_unix_server()
  File "/home/printer/moonraker/moonraker/components/extensions.py", line 122, in start_unix_server
    self.uds_server = await asyncio.start_unix_server(
  File "/usr/lib/python3.9/asyncio/streams.py", line 132, in start_unix_server
    return await loop.create_unix_server(factory, path, **kwds)
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 296, in create_unix_server
    sock.bind(path)
OSError: [Errno 22] Invalid argument
```

is there something I am missing out on?

**Comment by pataar** [comment]
Hi, what are you using as command / compose setup?

**Comment by shogowarrior** [comment]
Hey @pataar,

I tried with the given `docker-compose.yaml` with both CLI and VSC. I worked perfectly on my linux machine.
Seems to be something related to Mac docker in general.
